version: 0.2
env:
  variables:
    git_url: "https://github.com/talentedHippo/webaverse.git"
  parameter-store:
    ssh_key: id_ed25519
    ssh_pub: id_ed25519.pub
phases:
  pre_build:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Entered the pre-build phase...
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_ed25519   
      - echo "$ssh_pub" > ~/.ssh/id_ed25519.pub
      - chmod 600 ~/.ssh/id_ed25519
      - eval "$(ssh-agent -s)"
      - git init
      - git remote add origin "$git_url"
      - git fetch origin
      - git branch
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - git submodule init
      - git submodule update --recursive
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo running on production
      - npm run prod
artifacts:
    files: imagedefinitions.json
